package tk.ivybits.automata;

import java.awt.Insets;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

public class ControlFrame extends javax.swing.JDialog {

    private final AutomataGrid grid;

    /**
     * Creates new form ControlFrame
     */
    public ControlFrame(java.awt.Frame parent, boolean modal, final AutomataGrid grid) {
        super(parent, modal);
        this.grid = grid;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        automataScroller = new javax.swing.JScrollPane();
        automataList = new javax.swing.JPanel();
        delayLabel = new javax.swing.JLabel();
        delaySpinner = new javax.swing.JSpinner();
        stepButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controls");
        setMaximumSize(new java.awt.Dimension(155, 2147483647));
        setResizable(false);

        automataList.setLayout(new java.awt.GridLayout(0, 1));
        automataScroller.setViewportView(automataList);
        ButtonGroup exclusive = new ButtonGroup();
        for (final Automata a : Automata.values()) {
            JRadioButton select = new JRadioButton(a.display());
            select.setToolTipText(a.algorithm());
            select.addActionListener(new AbstractAction() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    grid.setAutomata(a);
                }
            });
            exclusive.add(select);
            select.setOpaque(true);
            select.setFocusPainted(false);
            select.setBackground(a.colour());
            select.setMargin(new Insets(0, 0, 0, 0));
            automataList.add(select);
        }
        exclusive.getElements().nextElement().setSelected(true);
        automataScroller.getVerticalScrollBar().setUnitIncrement(16);

        delayLabel.setText("generations/s");

        delaySpinner.setValue(4);

        stepButton.setText("Step");
        stepButton.setEnabled(false);
        stepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                stepButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.setMaximumSize(new java.awt.Dimension(61, 23));
        clearButton.setMinimumSize(new java.awt.Dimension(61, 23));
        clearButton.setPreferredSize(new java.awt.Dimension(61, 23));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        pauseButton.setText("Pause");
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(separator)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(pauseButton))
                    .addComponent(stepButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(delaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(delayLabel))
                    .addComponent(automataScroller))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pauseButton))
                .addGap(6, 6, 6)
                .addComponent(stepButton)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(delayLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(automataScroller, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        delaySpinner.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                grid.setGenerationsPerSecond((int) delaySpinner.getValue());
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        grid.reset();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void pauseButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        if (grid.isRunning()) {
            pauseButton.setText("Play");
        } else {
            pauseButton.setText("Pause");
        }
        grid.setRunning(!grid.isRunning());
        stepButton.setEnabled(!stepButton.isEnabled());
        delaySpinner.setEnabled(!delaySpinner.isEnabled());
        delayLabel.setEnabled(!delayLabel.isEnabled());
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void stepButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_stepButtonActionPerformed
        grid.tick();
    }//GEN-LAST:event_stepButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel automataList;
    private javax.swing.JScrollPane automataScroller;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel delayLabel;
    private javax.swing.JSpinner delaySpinner;
    private javax.swing.JButton pauseButton;
    private javax.swing.JSeparator separator;
    private javax.swing.JButton stepButton;
    // End of variables declaration//GEN-END:variables
}
